apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: jerrishpapa/my-app:cfda61ec7b399f03136bcd73440a9b2d737d4590
        ports:
        - containerPort: 3000

