apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: jerrishpapa/my-app:8e5999285ae613a061dc7f31f463cd99f51abe41
        ports:
        - containerPort: 3000

