apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: jerrishpapa/my-app:a205748ccc9c661c4d0147813af820511f08b0e4
        ports:
        - containerPort: 3000

