  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install kubectl
        run: |
          curl -sSL -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.7/2024-12-12/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd
          argocd version

      - name: Login to ArgoCD
        env:
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          echo "Logging into ArgoCD at: ${{ secrets.ARGOCD_SERVER }}"
          argocd login ${{ secrets.ARGOCD_SERVER }} \
              --username ${{ secrets.ARGOCD_USERNAME }} \
              --password "$ARGOCD_PASSWORD" \
              --insecure \
              --grpc-web
          
          echo "Verifying login..."
          argocd app list

      - name: Update deployment.yml with newly built image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout main
          git pull origin main
          
          echo "Updating deployment.yml..."
          sed -i "s+${{ secrets.DOCKERHUB_USERNAME }}/my-app.*+${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}+g" manifest/deployment.yml
          cat manifest/deployment.yml

      - name: Commit and Push Updated deployment.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add manifest/deployment.yml
          git commit -m "Update image to my-app:${{ github.sha }}" || echo "No changes to commit"
          git push origin main

      - name: Refresh ArgoCD App and Sync
        env:
          ARGOCD_OPTS: --grpc-web
        run: |
          echo "Syncing my-app with ArgoCD..."
          argocd app sync my-app
